// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQDbeMvgXFoj-W7iJEmLnz13f6I0vJws',
    appId: '1:199084862766:web:4ee213b24726fb97385ebf',
    messagingSenderId: '199084862766',
    projectId: 'heritage-db37e',
    authDomain: 'heritage-db37e.firebaseapp.com',
    storageBucket: 'heritage-db37e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-5proQdoHj-knDWn_AwUCwYPsykz_nHk',
    appId: '1:199084862766:android:21a35869490d82d1385ebf',
    messagingSenderId: '199084862766',
    projectId: 'heritage-db37e',
    storageBucket: 'heritage-db37e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8FUFTRcDJO5tzpbL9otZ-CPkO-_o-MQc',
    appId: '1:199084862766:ios:8b37de5462c70c8b385ebf',
    messagingSenderId: '199084862766',
    projectId: 'heritage-db37e',
    storageBucket: 'heritage-db37e.firebasestorage.app',
    iosBundleId: 'co.zw.coursehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8FUFTRcDJO5tzpbL9otZ-CPkO-_o-MQc',
    appId: '1:199084862766:ios:9f25436b2b7dd3b7385ebf',
    messagingSenderId: '199084862766',
    projectId: 'heritage-db37e',
    storageBucket: 'heritage-db37e.firebasestorage.app',
    iosBundleId: 'com.example.coursehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpQDbeMvgXFoj-W7iJEmLnz13f6I0vJws',
    appId: '1:199084862766:web:e870739d986390d7385ebf',
    messagingSenderId: '199084862766',
    projectId: 'heritage-db37e',
    authDomain: 'heritage-db37e.firebaseapp.com',
    storageBucket: 'heritage-db37e.firebasestorage.app',
  );

}